# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ricks garage
tagline:
description:      'Yet another infosec blog about reverse engineering, exploitation and hardware hacking,  paired with random thoughts and the usual banter about different things.'
url:              https://0x00rick.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           '0x00rick'
  url:            https://twitter.com/0x00rick

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
# version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/0x00rick


disqus:
  shortname:        0x00rick
