# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title.html

# Setup
title:            Hydeout
tagline:          'A Jekyll theme'
description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, updated.'
url:              http://hyde.getpoole.com
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Custom vars
version:          3.0.0
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

github:
  repo:           https://github.com/fongandrew/hydeout
